config/routes.rb
Rails.application.routes.draw do
  resources :cards do
    collection do
      get 'show_with_carousel'
    end
  end

  root :controller => 'cards', :action => 'index'
 

end

app/models/card.rb
class Card < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  def show_with_carousel
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card, html: {class: 'form-horizontal'}) do |f| %>
  <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :notes, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :notes, class: 'form-control' %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><h5><%= card.title %></h5></td>
        <td><h5><%= card.notes %></h5></td>
        <td>
	  <%= link_to card, class: 'btn btn-default' do %>
  	    <i class="glyphicon glyphicon-pushpin"></i> Display
	  <% end %>
        </td>
        <td>
          <%= link_to edit_card_path(card), class: 'btn btn-default' do %>
  	    <i class="glyphicon glyphicon-pencil"></i> Edit
	  <% end %>
        </td>
        <td>
          <%= link_to 'Remove', card, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-default'%>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path, class: 'btn btn-default' %>
<%= link_to 'Carousel View', show_with_carousel_cards_path, class: 'btn btn-default' %>

app/views/cards/new.html.erb
<h1>New Card</h1>
</br>
</br>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

    <style type="text/css">
      .card {
        width: 600px;
        height: 400px;
        margin: 20px;
      }
      .front, .back {
        border: 2px gray solid;
        padding: 10px;
      }
      .front {
        background-color: #ccc;
      }
      .back {
        background-color: #fff;
      }
    </style>

    <div id="main-container" class="container-fluid">
      <div class="row">
        <div id="sidebar" class="col-xs-3">
          <!-- sidebar content -->
        </div>
        <div id="main-content" class="col-xs-6">
	<div id="card-1" class="card"  style="background-color:#dddddd;"> 
	  <div class="front"> 
	    <p>
	      <h1 style="text-align:center;"><%= @card.title %></h1>
	    </p>
	  </div> 
	  <div class="back">
	    <p>
	      <h2 style="text-align:center;"><%= @card.notes %></h2>
	    </p>
	  </div> 
	</div>
        </div>
      </div>
    </div>

<script type="text/javascript">
    $(function(){
      // $(".card").flip();
      
      $("#card-1").flip({
        axis: "y", // y or x
        reverse: false, // true and false
        trigger: "click", // click or hover
        speed: 1000
      });
    });
</script>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/cards/show_with_carousel.html.erb
<p id="notice"><%= notice %></p>

<style type="text/css">
      .card {
        width: 600px;
        height: 400px;
        margin: 20px;
        margin-left: auto; 
        margin-right: auto; 
      }
      .front, .back {
        border: 2px gray solid;
        padding: 10px;
      }
      .front {
        background-color: #fff;
      }
      .front:hover {
        background-color: #eeeeee;
      }

      .back {
        background-color: #fff;
      }
      .item{
        background-color:#ddd;
	display:block;
        margin-left:auto;
        margin-right:auto; 
      }
      .carousel-caption{
	color:#000;
	position:static;
        margin-left:auto;
        margin-right:auto; 
      }
</style>

<h1 style="text-align:center;">Flash Cards</h1>
<h4>Tap To Flip</h4>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="false">
  <!-- Indicators -->
  <ol class="carousel-indicators">
  <% $i = 0 %>
  <% $a = true %>
  <% @cards.each do |card| %>
  <% if $a %>
  <li data-target="#carousel-example-generic" data-slide-to="<%= $i %>" class="active"></li>
  <% else %>
  <li data-target="#carousel-example-generic" data-slide-to="<%= $i %>"></li>
  <% end %>
  <% $a = false %>
  <% $i +=1 %>
  <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% $a = true %>
    <% @cards.each do |card| %>
    <% if $a %>
    <div class="item active">
    <% else %>
    <div class="item">
    <% end %>
    <div class="carousel-caption">
<div id="card-1" class="card"  style="background-color:#dddddd;">
          <div class="front">
            <p>
              <h1 style="text-align:center;"><%= card.title %></h1>
            </p>
          </div>
          <div class="back">
            <p>
              <h2 style="text-align:center;"><%= card.notes %></h2>
            </p>
          </div>
        </div>
    </div>
    </div>
    <% $a = false %>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script type="text/javascript">
    $(function(){
      $(".card").flip();
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlashcardApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navigation' %>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>

</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">RC Flashcards</a>
      <ul class="nav navbar-nav">
        <li><%= link_to 'New Card', new_card_path %></li>
        <li><%= link_to 'Carousel View', show_with_carousel_cards_path %></li>
      </ul>
    </div>
  </div>
</nav>